### PR TITLE
fix(config): add support for typed rules in Astro and fix naming convention rule for Astro endpoints

### LINKED ISSUE #414: Astro endpoints broken and typed rules not supported
### Your environment

n/a

### Describe the bug

The naming convention rule for Astro endpoints was misconfigured (sorry, my mistake) as it used `selector: 'function'` even though it should be `variable`.

Also, type checked rules don't work as we have not set project for virtual files created by `eslint-plugin-astro`.

### Project

eslint-config-sheriff

### Minimal reproduction

_No response_

### Steps to reproduce

_No response_

### Logs

```shell

```

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/AndreaPontrandolfo/sheriff/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing Guidelines on Issues](https://github.com/AndreaPontrandolfo/sheriff/blob/master/CONTRIBUTING.md#opening-a-new-issue).

### I will submit a PR

- [x] I'd be willing to submit a PR for this issue.

### PR DESCRIPTION
**Pull request by abemedia**
## Related Issue

Closes #414

## Summary by CodeRabbit

- New Features
  - Added ESLint support for virtual TypeScript produced from Astro files so those virtual files are parsed and analyzed.
- Bug Fixes
  - Improved naming-convention enforcement for Astro endpoint handlers to cover both variables and functions, tightening rules for function types.
- Chores
  - Added a changeset entry to publish a patch with these config updates.

### CODE REVIEW

File: packages/eslint-config-sheriff/src/getAstroConfig.ts [hunk 1]
```diff
@@ -60,6 +60,15 @@ export const getAstroConfig = (
...
     },
+    {
+      files: ['**/*.astro/*.ts'], // Virtual files created by eslint-plugin-astro.
+      languageOptions: {
+        parserOptions: {
+          parser: tseslint.parser,
+          project: customTSConfigPath || true,
+        },
+      },
+    },
```
Comment (abemedia) [inline packages/eslint-config-sheriff/src/getAstroConfig.ts:71]: This is required as `eslint-plugin-astro` creates virtual files for eslint for the `script` body.

**Comment by AndreaPontrandolfo** [comment]
@abemedia can you add the changeset?

**Review by AndreaPontrandolfo — APPROVED** [review]

**Comment by abemedia** [comment]
Sure, will do tomorrow.

**Comment by abemedia** [comment]
Have added it.

**Review by AndreaPontrandolfo — APPROVED** [review]
