### PR TITLE
fix(eslint-config-sheriff): Fix Astro TS integration and configure naming-convention for endpoints & components

### LINKED ISSUE #408: Astro integration broken
### Describe the bug

The config does not work for astro due to a bunch of misconfigurations

### 1. TypeScript integration broken
Since `languageOptions.parserOptions.parser` is not set to the `typescript-eslint` parser, using TypeScript in `*.astro` files' frontmatter causes errors.

### 2. naming-convention rule doesn't allow components
As `PascalCase` is not allowed in `*.astro` files (only in jsx/tsx) it is not possible to import and use Astro components.

### 3. naming-convention rule doesn't allow endpoints
Astro endpoints (see https://docs.astro.build/en/guides/endpoints/) require exported functions named `GET`, `POST`, `DELETE` etc. Since the naming-convention rule only allows `camelCase` creating an endpoint would currently cause a linter error.

### Project

eslint-config-sheriff

### Minimal reproduction

_No response_

### Steps to reproduce

_No response_

### Logs

```shell

```

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/AndreaPontrandolfo/sheriff/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing Guidelines on Issues](https://github.com/AndreaPontrandolfo/sheriff/blob/master/CONTRIBUTING.md#opening-a-new-issue).

### I will submit a PR

- [x] I'd be willing to submit a PR for this issue.

### PR DESCRIPTION
**Pull request by abemedia**
This pull request fixes various issues when using eslint-config-sheriff with Astro.

1. Set `languageOptions.parserOptions.parser` to allow writing TypeScript in Astro frontmatter.
2. Configure `@typescript-eslint/naming-convention` to allow PascalCase in `.astro` files (as components need to be PascalCase in JSX).
3.  Configure `@typescript-eslint/naming-convention` to allow Astro endpoints (see https://docs.astro.build/en/guides/endpoints/)

## Related Issue

Closes #408

## Other

While at it I also took the liberty to return the correct type from `getTsNamingConventionRule` so we can avoid using `@ts-expect-error`.

## Summary by CodeRabbit

* **New Features**
  * Extended linting rules to enforce TypeScript naming conventions for Astro files and JavaScript files in the pages directory, with special handling for Astro endpoint function names.

* **Refactor**
  * Improved type safety and structure in naming convention rule configuration.

* **Style**
  * Removed unnecessary TypeScript expect-error comments from configuration files.

### CODE REVIEW

File: packages/eslint-config-sheriff/src/getAstroConfig.ts [hunk 1]
```diff
@@ -56,5 +59,13 @@ export const getAstroConfig = (
         },
       },
     },
+    {
+      files: ['**/*.astro'],
+      rules: getTsNamingConventionRule({ isTsx: true }),
```
Comment (AndreaPontrandolfo) [inline packages/eslint-config-sheriff/src/getAstroConfig.ts:64]: I think you can include this into the above object.

File: packages/eslint-config-sheriff/src/utils/getTsNamingConventionRule.ts [hunk 2]
```diff
@@ -1,58 +1,72 @@
...
   isTsx: boolean;
+  isAstroEndpoint?: boolean;
 }
 
 export const getTsNamingConventionRule = ({
   isTsx,
-}: GetTsNamingConventionRuleOptions) => {
+  isAstroEndpoint,
+}: GetTsNamingConventionRuleOptions): TSESLint.FlatConfig.Rules => {
+  const options: unknown[] = [
```
Comment (AndreaPontrandolfo) [inline packages/eslint-config-sheriff/src/utils/getTsNamingConventionRule.ts:12]: Why are we specifying the type here? Doesn't `tsc` already infers a better one by itself?

**Review by AndreaPontrandolfo — CHANGES_REQUESTED** [review]

File: packages/eslint-config-sheriff/src/utils/getTsNamingConventionRule.ts (hunk 2 above)
Comment (abemedia) [reply packages/eslint-config-sheriff/src/utils/getTsNamingConventionRule.ts:12]: No because it doesn't have `filter` on any of these so will get a typescript error when appending below unless I do something like `as never` on the object I'm appending.

Comment (abemedia) [reply packages/eslint-config-sheriff/src/utils/getTsNamingConventionRule.ts:12]: If you'd prefer I could also just do what you do with `isTsx` e.g. `isAstroEndpoint && { ...` and `.filter(Boolean)`.

**Review by AndreaPontrandolfo — APPROVED** [review]

**Comment by AndreaPontrandolfo** [comment]
Hey @abemedia!

Your fix is released.

Unfortunately we didn't write the corresponding Changeset so it doesn't appear in the release notes, but it's there.

Thank you so much for your contribution!

**Comment by abemedia** [comment]
Thank you!
